### ISSUE TITLE
Javascript the Good Parts

### ISSUE THREAD

**Issue by iteles** [lrlna/personal-goals#2]
Hey :sparkles: 

I was looking for other `personal-goals` repos to inspire me to start my own after seeing @una's awesome example and came across yours.

I noticed you're reading Javascript the Good Parts as part of your goals and thought you might like to know that I've [written some notes on it](https://github.com/iteles/Javascript-the-Good-Parts-notes) - some people find them useful to help 'translate' the book into plain English :blush:

Best of luck and let me know if I can help!

**Comment by una** [comment]
I love this :two_hearts:

**Comment by iteles** [comment]
@una :sparkles: Thanks for all the wonderful inspiration! 😊🎉

**Comment by lrlna** [comment]
@iteles wow! that's an amazing set of notes! thanks :two_hearts: :tada:

**Comment by iteles** [comment]
@lrlna No problem, I'm just glad they might be helpful :ok_woman: 
Feel free to close this issue whenever you like, it was just to let you know :blush:
