### ISSUE TITLE
:sparkles: HARDWARE IS FUN :sparkles:

### ISSUE THREAD

**Issue by helenvholmes** [lrlna/personal-goals#3]
Some fun stuff you might find useful for your [Hardware goals](https://github.com/lrlna/personal-goals/blob/master/hardware.md):
- If you like the Flora, you might eventually want some [Gemmas](https://www.adafruit.com/gemma)! Floras are nice because they do [serial debugging](http://cl.ly/3T2I1z2F2L1k), but the Gemmas are tinier and easier to hide in clothing folds.
- _Definitely_ more expensive, but I really really like the [Spark Core kit](https://store.particle.io/collections/shields-and-kits). The Arduino Uno kits come with a lot of this stuff too, but the Spark Core kit comes with a bunch of resistors that the Uno kit didn't come with I don't think. (Plus it comes with a [prototyping breadboard](https://www.adafruit.com/product/571) _and_ a regular one, which is rad for when you're ready to solder up your stuff and consider it "done").
- Girl, you would love [Neopixels](https://www.adafruit.com/product/1586) and [El Wire](https://www.adafruit.com/product/545). Like, look at this stuff: [Light up skateboard???](https://www.youtube.com/watch?v=qeuOuhKDdnU) [LED sneakers???](https://learn.adafruit.com/firewalker-led-sneakers) [Whatever this thing is???](https://learn.adafruit.com/led-stego-flex-spike-hoodie/overview) anyway making stuff glow is awesome :rainbow: 
## Storing lots of tiny bits of hardware whatnot

Eventually owning all these little parts got crazy, so I invested in a [clear tackle box](http://www.amazon.com/Essential-12-inch-Plastic-Storage-Semi-clear/dp/B006R7TCM2/ref=sr_1_2?ie=UTF8&qid=1450387344&sr=8-2&keywords=clear+tackle+box) to store things. You know, in case your future looks like mine...
## Tutorials

I just linked to a bunch of Adafruit tutorials, but unlike web dev, seems like most stuff isn't in blogs but rather on Youtube + Instructables. Once you have your own projects, those are where I look for hardware answers. (SO for software like normal, though.)
### Fun Peeps to Follow
- [Becky Stern](https://www.youtube.com/user/bekathwia): Adafruit wearable/diy queen. :crown: 
- [Nodebotanist](https://twitter.com/nodebotanist): Nodebots! Made this super rad dress with LEDs.
- [Rwaldron](https://twitter.com/rwaldron): johnny-five.io creator~
- [Simone Giertz](https://www.youtube.com/channel/UC3KEoMzNz8eYnwBC34RaKCQ): Omg. I can't. She's too cool

Have fun makin' stuff!

**Comment by lrlna** [comment]
@helenvholmes You're such a super :star: !!! This is an amazing breakdown :heart: :heart_eyes_cat: :heart:

**Comment by eugenpirogoff** [comment]
This was made with a howto from Adafruit. Such a great project they came up with. 

https://github.com/eugenpirogoff/plush_controller

**Comment by lrlna** [comment]
that looks super awesome @eugenpirogoff :+1: :100:

**Comment by helenvholmes** [comment]
As uh, the "owner" of this issue (:joy:) your updates in your hardware.md look awesome! Gonna close this out :+1:

**Comment by lrlna** [comment]
I need to be better at this closing issues thing! sorryyyyyy :heart:
