### ISSUE TITLE
not a book suggestion but a suggestion none the less

### ISSUE THREAD

**Issue by rachsmithcodes** [lrlna/personal-goals#4]
todo: give yourself a pat on the back for being so awesome and having this awesome repo!!! :100: :sparkles: :top: :+1: :nail_care: :information_desk_person: :revolving_hearts: :100:

**Comment by lrlna** [comment]
Oh gee, thanks @rachsmithcodes :sparkles: :100: :heartbeat: :100: :sparkles:
